# Generated by Django 5.0 on 2024-10-21 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Content')),
                ('picture', models.ImageField(upload_to='posts_imgs/', verbose_name='Post picture/image')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='PostCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=600, verbose_name='Comment')),
                ('picture', models.ImageField(upload_to='comments_imgs/', verbose_name='Comment picture/image')),
                ('comm_date', models.DateTimeField(auto_now_add=True, verbose_name='Commented on')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postmodel')),
            ],
            options={
                'ordering': ['-comm_date'],
            },
        ),
    ]
