# Generated by Django 5.0 on 2024-10-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_superuser',
        ),
    ]
